'use strict';
const fullName = 'Ahmad El-Mowafy';
const isCool = true;
const totalPets = 2;
const empty = null;
let nothing;
console.log('Value of fullName:', fullName);
console.log('typeof fullName:', typeof fullName);
console.log('Value of isCool:', isCool);
console.log('typeof isCool:', typeof isCool);
console.log('Value of totalPets:', totalPets);
console.log('typeof totalPets:', typeof totalPets);
console.log('Value of empty:', empty);
console.log('typeof empty:', typeof empty);
console.log('Value of nothing:', nothing);
console.log('typeof nothing:', typeof nothing);
