'use strict';
const myWidth = 5;
const myLength = 3;
const area = myWidth * myLength;
console.log('Value of area:', area);
console.log('typeof area:', typeof area);
const bill = 86;
const payment = 100;
const change = payment - bill;
console.log('Value of change:', change);
console.log('typeof change:', typeof change);
const quizzes = 87;
const midterm = 91;
const final = 96;
const grade = (quizzes + midterm + final) / 3;
console.log('Value of grade:', grade);
console.log('typeof grade:', typeof grade);
const firstName = 'Ahmad';
const lastName = 'El-Mowafy';
const fullName = firstName + ' ' + lastName;
console.log('Value of fullName:', fullName);
console.log('typeof fullName:', typeof fullName);
const pH = 8;
const isAcidic = pH < 7;
console.log('Value of isAcidic:', isAcidic);
console.log('typeof isAcidic:', typeof isAcidic);
const headCount = 300;
const isSparta = headCount === 300;
console.log('Value of isSparta:', isSparta);
console.log('typeof isSparta:', typeof isSparta);
let motto = fullName;
motto += ' is the GOAT';
console.log('Value of motto:', motto);
console.log('typeof motto:', typeof motto);
